DEX_ABI = [
    # ─── Errors ───────────────────────────────────────────────────────────────
    {"inputs": [], "name": "AmountBelowMinimum",                "type": "error"},
    {"inputs": [], "name": "AmountOverflow",                    "type": "error"},
    {"inputs": [], "name": "AmountPrecisionExceedsBaseDecimals","type": "error"},
    {"inputs": [], "name": "AskExpired",                        "type": "error"},
    {"inputs": [], "name": "AskNotActive",                      "type": "error"},
    {"inputs": [], "name": "AskNotFound",                       "type": "error"},
    {"inputs": [], "name": "BaseMismatch",                      "type": "error"},
    {"inputs": [], "name": "BidExpired",                        "type": "error"},
    {"inputs": [], "name": "BidNotActive",                      "type": "error"},
    {"inputs": [], "name": "BidNotFound",                       "type": "error"},
    {"inputs": [], "name": "CannotWithdrawEscrowed",            "type": "error"},
    {"inputs": [], "name": "DeadlinePassed",                    "type": "error"},
    {"inputs": [], "name": "EnforcedPause",                     "type": "error"},
    {"inputs": [], "name": "ExceedsAskRemaining",               "type": "error"},
    {"inputs": [], "name": "ExceedsBidRemaining",               "type": "error"},
    {"inputs": [], "name": "ExpiryInPast",                      "type": "error"},
    {"inputs": [], "name": "ExpiryTooFar",                      "type": "error"},
    {"inputs": [], "name": "IdenticalTokens",                   "type": "error"},
    {"inputs": [], "name": "IncorrectBNBEscrow",                "type": "error"},
    {"inputs": [], "name": "InsufficientBidEscrow",             "type": "error"},
    {"inputs": [], "name": "InsufficientEscrow",                "type": "error"},
    {"inputs": [], "name": "InvalidAmountPrecision",            "type": "error"},
    {"inputs": [], "name": "InvalidMinBase",                    "type": "error"},
    {"inputs": [], "name": "InvalidMinQuote",                   "type": "error"},
    {"inputs": [], "name": "InvalidOrderId",                    "type": "error"},
    {"inputs": [], "name": "InvalidPricePrecision",             "type": "error"},
    {"inputs": [], "name": "MakerFeeExceedsProceeds",           "type": "error"},
    {"inputs": [], "name": "MarketNotActive",                   "type": "error"},
    {"inputs": [], "name": "MarketNotFound",                    "type": "error"},
    {"inputs": [], "name": "NativeTransferFailed",              "type": "error"},
    {"inputs": [], "name": "NotYourOrder",                      "type": "error"},
    {"inputs": [], "name": "OrderAlreadyExists",                "type": "error"},
    {"inputs": [], "name": "OrderExpired",                      "type": "error"},
    {"inputs": [], "name": "OrderNotActive",                    "type": "error"},
    {"inputs": [], "name": "OrderNotCancellable",               "type": "error"},
    {"inputs": [], "name": "OrderNotFound",                     "type": "error"},
    {"inputs": [], "name": "OrderValueBelowMinimum",            "type": "error"},
    {"inputs": [], "name": "PriceMismatch",                     "type": "error"},
    {"inputs": [], "name": "PriceOverflow",                     "type": "error"},
    {"inputs": [], "name": "PricePrecisionExceedsQuoteDecimals","type": "error"},
    {"inputs": [], "name": "QuoteEscrowRoundsToZero",           "type": "error"},
    {"inputs": [], "name": "QuoteRoundsToZero",                 "type": "error"},
    {"inputs": [], "name": "ReentrancyGuardReentrantCall",      "type": "error"},
    {"inputs": [{"internalType": "address", "name": "token", "type": "address"}],
     "name": "SafeERC20FailedOperation", "type": "error"},
    {"inputs": [], "name": "UnauthorizedSender",                "type": "error"},
    {"inputs": [], "name": "UnexpectedBNB",                     "type": "error"},
    {"inputs": [], "name": "UseNativeForBNB",                   "type": "error"},
    {"inputs": [], "name": "ZeroAddress",                       "type": "error"},
    {"inputs": [], "name": "ZeroAmount",                        "type": "error"},
    {"inputs": [], "name": "ZeroMinBase",                       "type": "error"},
    {"inputs": [], "name": "ZeroMinQuote",                      "type": "error"},
    {"inputs": [], "name": "ZeroPrice",                         "type": "error"},
    {"inputs": [], "name": "ZeroReceived",                      "type": "error"},

    # ─── Events ───────────────────────────────────────────────────────────────
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True,  "internalType": "bytes32",           "name": "orderId",      "type": "bytes32"},
            {"indexed": True,  "internalType": "address",           "name": "trader",       "type": "address"},
            {"indexed": False, "internalType": "enum Ordora.Side",  "name": "side",         "type": "uint8"},
            {"indexed": False, "internalType": "address",           "name": "baseToken",    "type": "address"},
            {"indexed": False, "internalType": "address",           "name": "quoteToken",   "type": "address"},
            {"indexed": False, "internalType": "uint256",           "name": "price",        "type": "uint256"},
            {"indexed": False, "internalType": "uint256",           "name": "amount",       "type": "uint256"},
            {"indexed": False, "internalType": "address",           "name": "escrowToken",  "type": "address"},
            {"indexed": False, "internalType": "uint256",           "name": "escrowAmount", "type": "uint256"},
            {"indexed": False, "internalType": "uint48",            "name": "expiresAt",    "type": "uint48"},
            {"indexed": False, "internalType": "uint48",            "name": "placedAt",     "type": "uint48"},
        ],
        "name": "OrderPlaced",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True,  "internalType": "bytes32", "name": "askOrderId",     "type": "bytes32"},
            {"indexed": True,  "internalType": "bytes32", "name": "bidOrderId",     "type": "bytes32"},
            {"indexed": False, "internalType": "uint256", "name": "baseAmount",     "type": "uint256"},
            {"indexed": False, "internalType": "uint256", "name": "quoteAmount",    "type": "uint256"},
            {"indexed": False, "internalType": "uint256", "name": "makerFee",       "type": "uint256"},
            {"indexed": False, "internalType": "uint256", "name": "takerFee",       "type": "uint256"},
            {"indexed": False, "internalType": "uint256", "name": "settlementPrice","type": "uint256"},
            {"indexed": False, "internalType": "uint128", "name": "askBaseFilled",  "type": "uint128"},
            {"indexed": False, "internalType": "uint128", "name": "bidBaseFilled",  "type": "uint128"},
            {"indexed": False, "internalType": "uint128", "name": "bidFilled",      "type": "uint128"},
            {"indexed": False, "internalType": "uint8",   "name": "askStatus",      "type": "uint8"},
            {"indexed": False, "internalType": "uint8",   "name": "bidStatus",      "type": "uint8"},
            {"indexed": False, "internalType": "address", "name": "askTrader",      "type": "address"},
            {"indexed": False, "internalType": "address", "name": "bidTrader",      "type": "address"},
            {"indexed": False, "internalType": "address", "name": "baseToken",      "type": "address"},
            {"indexed": False, "internalType": "address", "name": "quoteToken",     "type": "address"},
        ],
        "name": "OrderMatched",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True,  "internalType": "bytes32", "name": "orderId",      "type": "bytes32"},
            {"indexed": True,  "internalType": "address", "name": "trader",       "type": "address"},
            {"indexed": False, "internalType": "address", "name": "refundToken",  "type": "address"},
            {"indexed": False, "internalType": "uint256", "name": "refundAmount", "type": "uint256"},
            {"indexed": False, "internalType": "address", "name": "baseToken",    "type": "address"},
            {"indexed": False, "internalType": "address", "name": "quoteToken",   "type": "address"},
            {"indexed": False, "internalType": "uint8",   "name": "side",         "type": "uint8"},
            {"indexed": False, "internalType": "uint128", "name": "baseFilled",   "type": "uint128"},
            {"indexed": False, "internalType": "uint128", "name": "filled",       "type": "uint128"},
        ],
        "name": "OrderCancelled",
        "type": "event",
    },

    # ─── Constants (view) ─────────────────────────────────────────────────────
    {
        "inputs": [], "name": "DEFAULT_EXPIRY",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view", "type": "function",
    },
    {
        "inputs": [], "name": "paused",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
        "stateMutability": "view", "type": "function",
    },

    # ─── Read: Market & Order ─────────────────────────────────────────────────
    {
        "inputs": [
            {"internalType": "address", "name": "baseToken",  "type": "address"},
            {"internalType": "address", "name": "quoteToken", "type": "address"},
        ],
        "name": "getMarket",
        "outputs": [{
            "components": [
                {"internalType": "bool",    "name": "active",          "type": "bool"},
                {"internalType": "uint8",   "name": "baseDecimals",    "type": "uint8"},
                {"internalType": "uint8",   "name": "quoteDecimals",   "type": "uint8"},
                {"internalType": "uint8",   "name": "pricePrecision",  "type": "uint8"},
                {"internalType": "uint8",   "name": "amountPrecision", "type": "uint8"},
                {"internalType": "uint128", "name": "minBaseAmount",   "type": "uint128"},
                {"internalType": "uint128", "name": "minQuoteAmount",  "type": "uint128"},
            ],
            "internalType": "struct Ordora.Market", "name": "", "type": "tuple",
        }],
        "stateMutability": "view", "type": "function",
    },
    {
        "inputs": [{"internalType": "bytes32", "name": "orderId", "type": "bytes32"}],
        "name": "getOrder",
        "outputs": [{
            "components": [
                {"internalType": "address",            "name": "trader",       "type": "address"},
                {"internalType": "enum Ordora.Side",   "name": "side",         "type": "uint8"},
                {"internalType": "enum Ordora.Status", "name": "status",       "type": "uint8"},
                {"internalType": "uint8",              "name": "baseDecimals", "type": "uint8"},
                {"internalType": "address",            "name": "baseToken",    "type": "address"},
                {"internalType": "uint48",             "name": "expiresAt",    "type": "uint48"},
                {"internalType": "uint48",             "name": "placedAt",     "type": "uint48"},
                {"internalType": "address",            "name": "quoteToken",   "type": "address"},
                {"internalType": "uint128",            "name": "price",        "type": "uint128"},
                {"internalType": "uint128",            "name": "amount",       "type": "uint128"},
                {"internalType": "uint128",            "name": "filled",       "type": "uint128"},
                {"internalType": "uint128",            "name": "baseFilled",   "type": "uint128"},
                {"internalType": "uint128",            "name": "escrowAmount", "type": "uint128"},
            ],
            "internalType": "struct Ordora.Order", "name": "", "type": "tuple",
        }],
        "stateMutability": "view", "type": "function",
    },
    {
        "inputs": [{"internalType": "bytes32", "name": "orderId", "type": "bytes32"}],
        "name": "remaining",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view", "type": "function",
    },

    # ─── Write: Trader Functions ──────────────────────────────────────────────
    {
        "inputs": [
            {"internalType": "bytes32", "name": "orderId",    "type": "bytes32"},
            {"internalType": "uint256", "name": "nonce",      "type": "uint256"},
            {"internalType": "address", "name": "baseToken",  "type": "address"},
            {"internalType": "address", "name": "quoteToken", "type": "address"},
            {"internalType": "uint256", "name": "price",      "type": "uint256"},
            {"internalType": "uint256", "name": "amount",     "type": "uint256"},
            {"internalType": "uint256", "name": "expiresAt",  "type": "uint256"},
        ],
        "name": "placeAskToken",
        "outputs": [],
        "stateMutability": "nonpayable", "type": "function",
    },
    {
        "inputs": [
            {"internalType": "bytes32", "name": "orderId",    "type": "bytes32"},
            {"internalType": "uint256", "name": "nonce",      "type": "uint256"},
            {"internalType": "address", "name": "quoteToken", "type": "address"},
            {"internalType": "uint256", "name": "price",      "type": "uint256"},
            {"internalType": "uint256", "name": "expiresAt",  "type": "uint256"},
        ],
        "name": "placeAskNative",
        "outputs": [],
        "stateMutability": "payable", "type": "function",
    },
    {
        "inputs": [
            {"internalType": "bytes32", "name": "orderId",    "type": "bytes32"},
            {"internalType": "uint256", "name": "nonce",      "type": "uint256"},
            {"internalType": "address", "name": "baseToken",  "type": "address"},
            {"internalType": "address", "name": "quoteToken", "type": "address"},
            {"internalType": "uint256", "name": "price",      "type": "uint256"},
            {"internalType": "uint256", "name": "amount",     "type": "uint256"},
            {"internalType": "uint256", "name": "expiresAt",  "type": "uint256"},
        ],
        "name": "placeBid",
        "outputs": [],
        "stateMutability": "payable", "type": "function",
    },
    {
        "inputs": [{"internalType": "bytes32", "name": "orderId", "type": "bytes32"}],
        "name": "cancelOrder",
        "outputs": [],
        "stateMutability": "nonpayable", "type": "function",
    },
]
